#================================================
# GLOBAL SETTINGS
#================================================

# DEFAULT PROFILE
# If no URL pattern matches, this profile will be used.
# If not set, Chrome's built-in default ("Default") is used.
# default_profile = "Default"  # Uncomment and change as needed

# CHROME PATH
# Specify a custom path to your Chrome executable.
# Comment out to use auto-detection.
#
# Linux example:
# chrome_path = "/usr/bin/google-chrome-stable"
#
# macOS example:
# chrome_path = "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
#
# Windows example:
# chrome_path = "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe"

#================================================
# PROFILE CONFIGURATIONS
#================================================
# Define which Chrome profile to use for which URLs

# PROFILE DIRECTORY TIPS:
# - Find your profile directories at:
#   Linux: ~/.config/google-chrome/
#   macOS: ~/Library/Application Support/Google/Chrome/
#   Windows: %LOCALAPPDATA%\Google\Chrome\User Data\
# - Common values are "Default", "Profile 1", "Profile 2", etc.
# - Check chrome://version in Chrome to see your current Profile Path

# Work profile example
[[profiles]]
name = "Work"
profile_directory = "Profile 1"
url_patterns = ["github.com", "work.example.com", "jira.mycompany.net"]

# Personal profile example
# [[profiles]]
# name = "Shopping"
# profile_directory = "Profile 2"
# url_patterns = ["amazon.com", "ebay.com"]
#
# Add more profile mappings as needed.
